on: release
name: Deploy Extension
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install --unsafe-perm
    - name: Publish
      uses: lannonbr/vsce-action@master
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      with:
        args: publish -p $VSCE_TOKEN
